<?php

declare(strict_types=1);

namespace SixtyEightPublishers\TracyGitVersion\Bridge\Tracy;

use Tracy\Helpers;

/** @var \SixtyEightPublishers\TracyGitVersion\Repository\GitRepositoryInterface $gitRepository */
/** @var \SixtyEightPublishers\TracyGitVersion\Bridge\Tracy\Block\BlockInterface[] $blocks */

?>

<style class="tracy-debug">
	#tracy-debug .nette-gitVersionPanel {
		min-width: 100%;
	}

	#tracy-debug .nette-gitVersionPanel table {
		width: 100%;
		white-space: nowrap;
	}

    #tracy-debug .nette-gitVersionPanel table tr th {
        width: 1px;
        white-space: nowrap;
    }

    #tracy-debug .nette-gitVersionPanel .source {
        margin-top: 20px;
        text-align: center;
    }
</style>

<h1>Git Version</h1>

<div class="tracy-inner nette-gitVersionPanel">
	<div class="tracy-inner-container">
		<?php foreach($blocks as $block): echo $block->render($gitRepository); endforeach; ?>
	</div>

    <div class="tracy-inner-container">
        <p class="source">
            <code>Source: <?php echo Helpers::escapeHtml($gitRepository->getSource()) ?></code>
        </p>
    </div>
</div>
