<?php

declare(strict_types=1);

namespace SixtyEightPublishers\TracyGitVersion\Bridge\Tracy;

use Tracy\Helpers;

/** @var string|null $caption */
/** @var array<string, string> $rows */

?>

<?php if (NULL !== $caption): ?>
<h2><?php echo Helpers::escapeHtml($caption) ?></h2>
<?php endif; ?>

<table>
    <?php foreach ($rows as $k => $v): ?>
    <tr>
        <th><?php echo Helpers::escapeHtml($k) ?></th>
        <td><?php echo Helpers::escapeHtml($v) ?></td>
    </tr>
    <?php endforeach; ?>
</table>
