#!/usr/bin/env php
<?php

$possibleAutoloadFiles = [__DIR__ . '/../../autoload.php', __DIR__ . '/../autoload.php', __DIR__ . '/vendor/autoload.php'];
$autoloadFile = null;

foreach ($possibleAutoloadFiles as $possibleAutoloadFile) {
    if (file_exists($possibleAutoloadFile)) {
        $autoloadFile = $possibleAutoloadFile;

        break;
    }
}

if (null === $autoloadFile) {
    throw new RuntimeException('Unable to find composer autoload.php file.');
}

require_once $autoloadFile;

unset($possibleAutoloadFiles, $possibleAutoloadFile, $autoloadFile);

use SixtyEightPublishers\TracyGitVersion\Bridge\Symfony\Console\Application;

$application = new Application();
$application->run();

__HALT_COMPILER();
