name: Tests

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Unit Tests [PHP ${{ matrix.php-versions }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-progress --prefer-dist --prefer-stable --optimize-autoloader --quiet

      - name: Run tests
        run: vendor/bin/tester -C -s ./tests

      - name: Install dependencies (lowest)
        run: composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable --optimize-autoloader --quiet

      - name: Run tests
        run: vendor/bin/tester -C -s ./tests
